$(document).ready(function () {
    console.log("Ready")
    var arrTurns = []
    var square = $(".square")
    //console.log(arrTurns)
    square.one("click", function (evt) {
        var squares = $(evt.target)
        if (arrTurns.length == 0) {
            squares.addClass("o")
            arrTurns.push("O")
            //console.log(arrTurns)
        } else if (arrTurns[arrTurns.length - 1] == "O") {
            squares.addClass("x")
            arrTurns.push("X")
        } else {
            squares.addClass("o")
            arrTurns.push("O")
        }
        console.log(arrTurns)
    })
    square.mouseout(function () {
        if ($(".square:eq(0)").hasClass("x") && $(".square:eq(1)").hasClass("x") && $(".square:eq(2)").hasClass("x")) {
            //console.log("funciona")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(4)").removeClass("x")
            $(".square:eq(4)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square:eq(6)").removeClass("x")
            $(".square:eq(6)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square:eq(8)").removeClass("x")
            $(".square:eq(8)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el primer Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(0)").hasClass("x") && $(".square:eq(3)").hasClass("x") && $(".square:eq(6)").hasClass("x")) {
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(2)").removeClass("x")
            $(".square:eq(2)").removeClass("o")
            $(".square:eq(4)").removeClass("x")
            $(".square:eq(4)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square:eq(8)").removeClass("x")
            $(".square:eq(8)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el primer Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(0)").hasClass("x") && $(".square:eq(4)").hasClass("x") && $(".square:eq(8)").hasClass("x")) {
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(2)").removeClass("x")
            $(".square:eq(2)").removeClass("o")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square:eq(6)").removeClass("x")
            $(".square:eq(6)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el primer Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(1)").hasClass("x") && $(".square:eq(4)").hasClass("x") && $(".square:eq(7)").hasClass("x")) {
            $(".square:eq(2)").removeClass("x")
            $(".square:eq(2)").removeClass("o")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square:eq(6)").removeClass("x")
            $(".square:eq(6)").removeClass("o")
            $(".square:eq(0)").removeClass("x")
            $(".square:eq(0)").removeClass("o")
            $(".square:eq(8)").removeClass("x")
            $(".square:eq(8)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el primer Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(2)").hasClass("x") && $(".square:eq(5)").hasClass("x") && $(".square:eq(8)").hasClass("x")) {
            $(".square:eq(0)").removeClass("x")
            $(".square:eq(0)").removeClass("o")
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(4)").removeClass("x")
            $(".square:eq(4)").removeClass("o")
            $(".square:eq(6)").removeClass("x")
            $(".square:eq(6)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el primer Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(2)").hasClass("x") && $(".square:eq(4)").hasClass("x") && $(".square:eq(6)").hasClass("x")) {
            $(".square:eq(0)").removeClass("x")
            $(".square:eq(0)").removeClass("o")
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square:eq(8)").removeClass("x")
            $(".square:eq(8)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el primer Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(3)").hasClass("x") && $(".square:eq(4)").hasClass("x") && $(".square:eq(5)").hasClass("x")) {
            $(".square:eq(0)").removeClass("x")
            $(".square:eq(0)").removeClass("o")
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(2)").removeClass("x")
            $(".square:eq(2)").removeClass("o")
            $(".square:eq(6)").removeClass("x")
            $(".square:eq(6)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square:eq(8)").removeClass("x")
            $(".square:eq(8)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el primer Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(6)").hasClass("x") && $(".square:eq(7)").hasClass("x") && $(".square:eq(8)").hasClass("x")) {
            $(".square:eq(0)").removeClass("x")
            $(".square:eq(0)").removeClass("o")
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(2)").removeClass("x")
            $(".square:eq(2)").removeClass("o")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(4)").removeClass("x")
            $(".square:eq(4)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el segundo Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(0)").hasClass("o") && $(".square:eq(1)").hasClass("o") && $(".square:eq(2)").hasClass("o")) {
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(4)").removeClass("x")
            $(".square:eq(4)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square:eq(6)").removeClass("x")
            $(".square:eq(6)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square:eq(8)").removeClass("x")
            $(".square:eq(8)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el segundo Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(0)").hasClass("o") && $(".square:eq(3)").hasClass("o") && $(".square:eq(6)").hasClass("o")) {
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(2)").removeClass("x")
            $(".square:eq(2)").removeClass("o")
            $(".square:eq(4)").removeClass("x")
            $(".square:eq(4)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square:eq(8)").removeClass("x")
            $(".square:eq(8)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el segundo Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(0)").hasClass("o") && $(".square:eq(4)").hasClass("o") && $(".square:eq(8)").hasClass("o")) {
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(2)").removeClass("x")
            $(".square:eq(2)").removeClass("o")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square:eq(6)").removeClass("x")
            $(".square:eq(6)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el segundo Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(1)").hasClass("o") && $(".square:eq(4)").hasClass("o") && $(".square:eq(7)").hasClass("o")) {
            $(".square:eq(2)").removeClass("x")
            $(".square:eq(2)").removeClass("o")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square:eq(6)").removeClass("x")
            $(".square:eq(6)").removeClass("o")
            $(".square:eq(0)").removeClass("x")
            $(".square:eq(0)").removeClass("o")
            $(".square:eq(8)").removeClass("x")
            $(".square:eq(8)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el segundo Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(2)").hasClass("o") && $(".square:eq(5)").hasClass("o") && $(".square:eq(8)").hasClass("o")) {
            $(".square:eq(0)").removeClass("x")
            $(".square:eq(0)").removeClass("o")
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(4)").removeClass("x")
            $(".square:eq(4)").removeClass("o")
            $(".square:eq(6)").removeClass("x")
            $(".square:eq(6)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el segundo Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(2)").hasClass("o") && $(".square:eq(4)").hasClass("o") && $(".square:eq(6)").hasClass("o")) {
            $(".square:eq(0)").removeClass("x")
            $(".square:eq(0)").removeClass("o")
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square:eq(8)").removeClass("x")
            $(".square:eq(8)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el segundo Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(3)").hasClass("o") && $(".square:eq(4)").hasClass("o") && $(".square:eq(5)").hasClass("o")) {
            $(".square:eq(0)").removeClass("x")
            $(".square:eq(0)").removeClass("o")
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(2)").removeClass("x")
            $(".square:eq(2)").removeClass("o")
            $(".square:eq(6)").removeClass("x")
            $(".square:eq(6)").removeClass("o")
            $(".square:eq(7)").removeClass("x")
            $(".square:eq(7)").removeClass("o")
            $(".square:eq(8)").removeClass("x")
            $(".square:eq(8)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el segundo Jugador!")
                $(".square").off()
            })
        } if ($(".square:eq(6)").hasClass("o") && $(".square:eq(7)").hasClass("o") && $(".square:eq(8)").hasClass("o")) {
            $(".square:eq(0)").removeClass("x")
            $(".square:eq(0)").removeClass("o")
            $(".square:eq(1)").removeClass("x")
            $(".square:eq(1)").removeClass("o")
            $(".square:eq(2)").removeClass("x")
            $(".square:eq(2)").removeClass("o")
            $(".square:eq(3)").removeClass("x")
            $(".square:eq(3)").removeClass("o")
            $(".square:eq(4)").removeClass("x")
            $(".square:eq(4)").removeClass("o")
            $(".square:eq(5)").removeClass("x")
            $(".square:eq(5)").removeClass("o")
            $(".square").on("mouseout", function () {
                alert("Ganó el segundo Jugador!")
                $(".square").off()
            })
        }
    })
})

